name: Build and Test
# TODO: do not trigger action for some document file update

# This workflow is triggered on pushes or pull request to the repository.
on:
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'scripts/**'
      - 'internal/**'
      - 'cmd/**'
      - 'build/**'
      - '.github/workflows/main.yaml'
      - '.env'
      - docker-compose.yml
      - Makefile
      - '!**.md'
      - '!build/ci/jenkins/**'

jobs:
  builder:
    name: Build and Test AMD64 ${{ matrix.os }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu18.04, centos7]
    env:
      OS_NAME: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache CCache Volumes
        uses: actions/cache@v1
        with:
          path: .docker/amd64-${{ matrix.os }}-ccache
          key: ${{ matrix.os }}-ccache-${{ hashFiles('internal/core/**') }}
          restore-keys: ${{ matrix.os }}-ccache-
      - name: Cache Go Mod Volumes
        uses: actions/cache@v1
        with:
          path: .docker/amd64-${{ matrix.os }}-go-mod
          key: ${{ matrix.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ matrix.os }}-go-mod-
      - name: Start Service
        shell: bash
        run: |
          docker-compose up -d pulsar etcd minio
      - name: Build and UnitTest
        env:
          CHECK_BUILDER: "1"
        run: |
          ./build/builder.sh /bin/bash -c "make check-proto-product && make unittest"
